### ISSUE TITLE
Add Ability from Query Records to pass WHERE Clause to Update Record With No File

### ISSUE THREAD

**Issue by AndyHaas** [jetstreamapp/jetstream#199]
Would love the ability to pass the WHERE Clause from query Records to the Action "Update Record with No File" this would allow us to not have to copy and paste the where clause each time.

**Comment by AndyHaas** [comment]
![Screenshot 2023-03-10 110419](https://user-images.githubusercontent.com/22582720/224377995-a433f4de-2e57-427d-8552-be914b77c8b2.png)
![Screenshot 2023-03-10 110021](https://user-images.githubusercontent.com/22582720/224377999-9c561238-3203-4a01-a2f4-9b7561915a14.png)
![Screenshot 2023-03-10 110008](https://user-images.githubusercontent.com/22582720/224378000-ba848e3f-7301-476d-8a0b-000167a415c2.png)

**Comment by paustint** [comment]
@AndyHaas - I put some thought into this and have an alternative suggestion on how to solve.

Instead of going from query results to the load without file page, I am thinking this flow:
1. Query Records
2. On the query results, there is a new option on the page "Bulk Update Records"
3. Clicking opens up a modal
4. The modal is basically the same as the load without file page
5. Option to apply just to selected records or all records (and if there are more records via "load more" option to apply to everything)
6. You choose what field you want to update (could even allow multiple fields)
7. You indicate what you want the value to be (identical options as on load page)
8. Data is loaded in


Let me know what you think - I think this will be a more streamlined flow instead of switching pages.

And this is where I am thinking of including the option, regardless of approach above:

![image](https://user-images.githubusercontent.com/5461649/224458748-d325c1fa-c6ce-4f64-b6b9-15d92efecd8f.png)

**Comment by AndyHaas** [comment]
Sounds like a great option
