### ISSUE TITLE
Related Field Drop Down | Update UI for Object

### ISSUE THREAD

**Issue by AndyHaas** [jetstreamapp/jetstream#279]
Can we make this any better? 

Maybe object on a second line? Bold? 

![Screenshot 2023-04-06 at 11 19 59 AM](https://user-images.githubusercontent.com/22582720/230438609-fa61e402-e717-4551-b7d8-4dc438557912.png)

**Comment by AndyHaas** [comment]
If you want to mock up some ideas and let us vote I am down for that

**Comment by paustint** [comment]
@AndyHaas - We can do either of those options.

I kept it one one line so it didn't take up a bunch of space since it is a secondary option and was taking a lead from how Salesforce does this on their Flow Builder.

I think `#1` below looks pretty decent, it does take up a little more room but I don't think that is a big deal.

Let me know what you think.

# 1 - Smaller text and object type on new line
<img width="356" alt="image" src="https://user-images.githubusercontent.com/5461649/230505487-a692be43-9e3c-4862-a130-e89f7d33a259.png">


# 2 - Smaller text and object on same line
fixed alignment of text - but this is basically the same as we have now

<img width="276" alt="image" src="https://user-images.githubusercontent.com/5461649/230505908-d8302e8a-af8b-4fd3-a95d-166f9514502c.png">

# 3 - Smaller text and bold label, secondary object name

<img width="263" alt="image" src="https://user-images.githubusercontent.com/5461649/230506213-8dd68190-06cd-47d1-a293-9db145307cdf.png">

**Comment by paustint** [comment]
Opened a PR for approach 1 above

<img width="609" alt="image" src="https://user-images.githubusercontent.com/5461649/230507764-6087038b-7400-42d0-8d77-0de464bf9a1e.png">

**Comment by AndyHaas** [comment]
Option 1 is what I would go with. Matches sf  way
