### ISSUE TITLE
Choose a Verification Method

### ISSUE THREAD

**Issue by TijsDeBelie** [jetstreamapp/jetstream#716]
**Describe the bug and steps to reproduce**
When you have an external MFA method set up that is not the Salesforce authenticator (E.G Okta, Microsoft Authenticator, ...)
Open any record from Jetstream

**Expected behavior**
You navigate to the record in salesforce, or you are routed to the login page of salesforce to authenticate (if you are not yet authenticated in that browser)

**Actual behavior**
You are rooted to choose a verification method page of Salesforce (even when already authenticated in that browser)
It also auto blocks any further normal authentication attempts by prompting I have to register the salesforce authenticator. 
Our org already has an MFA method, and it only occurs when opening URL's from Jetstream

![image](https://github.com/jetstreamapp/jetstream/assets/22316489/0b974338-2667-4a38-9d39-cf74a5eeb256)

**Browser and operating system:**

Brave Browser
Windows 11

**Comment by paustint** [comment]
@TijsDeBelie - hmm, I have not encountered this one previously. It is possible that you might have high assurance sessions or some other session configuration that prompts this.

Jetstream uses [Salesforce's frontdoor feature](https://help.salesforce.com/s/articleView?id=sf.security_frontdoorjsp.htm&type=5) when you click on a link so that you don't have to login, and Salesforce controls the entire experience after you leave Jetstream.

👉  We are working on a user setting that will allow you to disable this behavior so that all links will not attempt to auto-login and will just direct you directly to Salesforce.

**Comment by paustint** [comment]
@TijsDeBelie - A fix has been deployed for this, you will want to enable this setting in which case Jetstream will not attempt to login to Salesforce with your Jetstream session, but instead just redirect you to the page on salesforce.

![image](https://github.com/jetstreamapp/jetstream/assets/5461649/702dc6c0-3d47-467e-b436-974049c14d20)

**Comment by TijsDeBelie** [comment]
Hello, 

Thank you for this change, I just confirmed it works now as expected. 

Kind regards

Tijs
