### ISSUE TITLE
Manage Permissions FilterBy column resets when another column is modified

### ISSUE THREAD

**Issue by chris-varney-novidea** [jetstreamapp/jetstream#756]
**### Description**

When using the Manage Permissions feature, I select the Profiles, Permission Sets, and Objects I want to manage access for. Once the query returns, I am taken to a UI which allows me to modify the Object Settings, Tab Settings, and Field Settings per Profile or Permission Set.

If I select to filter by any of the column headers and uncheck either TRUE or FALSE, the list applies the filter appropriately and I am able to view the updated table without issue; however, IF I interact with anything else in the table, the list filter is cleared and the table refreshes to its original state.

**### Expected Behavior**

The system should allow the filtered column to remain untouched, allowing the end user to reconcile differences between the columns more easily, if comparing access between two or more Profiles and Permission Sets. For example, if an end user is verifying that the CREATE access is the same between two Profiles, they should be able to filter their source of truth Profile to show only objects where CREATE = TRUE, AND be able to modify the CREATE column of the second Profile to match without the filter resetting.

Google Chrome / macOS Sonoma 14.1.2

**Comment by paustint** [comment]
@chris-varney-novidea - This one is turning out to be a bit difficult to get the great behavior this would be ideal.

I would love to have the table remain stable across changes to the data (e.x. even when a row is modified, the table remains "as-is")
I am working on a minor improvement to make it so that the filter does not get reset when a value is changed, but the sub-optimal behavior is that the selected row will disappear since it no longer meets the filter criteria.

See a demo: https://jam.dev/c/f3d9d54d-4538-4bac-ba2d-90824f286733

I will open a new ticket to figure out how to improve this behavior - but I think it is at least somewhat better than the current behavior.

If you have any additional feedback, let me know.
